/**
 * Client-side Firebase singleton.
 *
 * Initializes the app once, wires the Firebase Emulator Suite when
 * NEXT_PUBLIC_EMULATOR=true, and optionally enables Firebase App Check.
 * Everything is guarded so it can be safely imported during SSR.
 */
'use client'

import { initializeApp, getApps, type FirebaseApp } from 'firebase/app'
import {
  getAuth,
  connectAuthEmulator,
  type Auth,
  type User,
} from 'firebase/auth'
import {
  getFirestore,
  connectFirestoreEmulator,
  type Firestore,
} from 'firebase/firestore'
import {
  getStorage,
  connectStorageEmulator,
  type FirebaseStorage,
} from 'firebase/storage'
import {
  getFunctions,
  connectFunctionsEmulator,
  type Functions,
} from 'firebase/functions'
import {
  initializeAppCheck,
  ReCaptchaV3Provider,
  type AppCheck,
} from 'firebase/app-check'

import {
  appCheckDebugToken,
  appCheckRecaptchaKey,
  EMULATOR_AUTH_PORT,
  EMULATOR_FIRESTORE_PORT,
  EMULATOR_HOST,
  EMULATOR_STORAGE_PORT,
  isEmulator,
  readFirebaseEnv,
} from './config'

declare global {
  interface Window {
    FIREBASE_APPCHECK_DEBUG_TOKEN?: string
  }
}

let app: FirebaseApp | null = null
let auth: Auth | null = null
let db: Firestore | null = null
let storage: FirebaseStorage | null = null
let functions: Functions | null = null
let appCheck: AppCheck | null = null

function ensureApp(): FirebaseApp {
  if (app) return app
  if (getApps().length > 0) {
    app = getApps()[0]
    return app
  }

  // In the browser, allow App Check debug tokens in development.
  if (typeof window !== 'undefined' && appCheckDebugToken) {
    window.FIREBASE_APPCHECK_DEBUG_TOKEN = appCheckDebugToken
  }

  app = initializeApp(readFirebaseEnv())

  if (isEmulator && typeof window !== 'undefined') {
    // Emulator credentials are generated by the emulator and accepted locally.
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    ;(app as any).automaticDataCollectionEnabled = false
  }

  return app
}

export function getFirebaseApp(): FirebaseApp {
  return ensureApp()
}

export function getFirebaseAuth(): Auth {
  if (auth) return auth
  const current = getAuth(ensureApp())
  if (isEmulator && typeof window !== 'undefined') {
    // Emulator auth accepts any email/password combination.
    connectAuthEmulator(current, `http://${EMULATOR_HOST}:${EMULATOR_AUTH_PORT}`, {
      disableWarnings: true,
    })
  }
  auth = current
  return auth
}

export function getFirestoreDb(): Firestore {
  if (db) return db
  const current = getFirestore(ensureApp())
  if (isEmulator && typeof window !== 'undefined') {
    connectFirestoreEmulator(current, EMULATOR_HOST, EMULATOR_FIRESTORE_PORT)
  }
  db = current
  return db
}

export function getFirebaseStorage(): FirebaseStorage {
  if (storage) return storage
  const current = getStorage(ensureApp())
  if (isEmulator && typeof window !== 'undefined') {
    connectStorageEmulator(current, EMULATOR_HOST, EMULATOR_STORAGE_PORT)
  }
  storage = current
  return storage
}

export function getFirebaseFunctions(): Functions {
  if (functions) return functions
  const current = getFunctions(ensureApp())
  if (isEmulator && typeof window !== 'undefined') {
    connectFunctionsEmulator(current, EMULATOR_HOST, 5001)
  }
  functions = current
  return functions
}

export function getFirebaseAppCheck(): AppCheck | null {
  // App Check is opt-in via env. When unconfigured (emulator or not yet set
  // up), the app works without it — this keeps development friction low while
  // keeping the production path ready.
  if (appCheck) return appCheck
  if (!appCheckRecaptchaKey) return null
  appCheck = initializeAppCheck(ensureApp(), {
    provider: new ReCaptchaV3Provider(appCheckRecaptchaKey),
    isTokenAutoRefreshEnabled: true,
  })
  return appCheck
}

/** Current auth user or null. Convenience for non-hook call sites. */
export async function getCurrentUser(): Promise<User | null> {
  const current = getFirebaseAuth()
  await current.authStateReady()
  return current.currentUser
}

export { isEmulator }
